# Generated by Django 3.2 on 2021-04-10 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1500)),
                ('subject', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 10, 17, 16, 45, 607239))),
            ],
        ),
    ]
