# Generated by Django 3.2 on 2021-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('login_date', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=200)),
                ('receiver', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=1500)),
                ('subject', models.CharField(default='', max_length=300)),
                ('creation_date', models.DateTimeField(default='')),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
    ]
