# Generated by Django 3.2 on 2021-04-10 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 10, 17, 19, 59, 954918)),
        ),
    ]
