# Generated by Django 3.2 on 2021-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinusers',
            name='login_date',
        ),
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
