# Generated by Django 3.2 on 2021-04-10 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0002_alter_message_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 4, 10, 17, 23, 17, 374606)),
        ),
    ]
