# Generated by Django 3.2 on 2021-04-10 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0003_alter_message_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default='', verbose_name=datetime.datetime(2021, 4, 10, 17, 31, 26, 211489)),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=300),
        ),
    ]
