# Generated by Django 3.2 on 2021-04-10 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0004_auto_20210410_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default='', verbose_name=datetime.datetime(2021, 4, 10, 17, 49, 36, 782453)),
        ),
    ]
