# Generated by Django 3.2 on 2021-04-10 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0006_alter_message_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default='', verbose_name=datetime.datetime(2021, 4, 10, 18, 9, 54, 227960)),
        ),
    ]
