# Generated by Django 3.2 on 2021-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0008_alter_message_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_date',
            field=models.DateTimeField(default=''),
        ),
    ]
