# Generated by Django 3.2 on 2021-04-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0009_alter_message_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=False),
        ),
    ]
