# Generated by Django 3.2 on 2021-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0010_message_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
