# Generated by Django 3.2 on 2021-04-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0011_alter_message_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
